### ISSUE TITLE
[Bug] Falha ao requisitar 'próximo' e 'anterior' após realizar uma busca por nome (str) do Pokémon 

### ISSUE THREAD

**Issue by bakudas** [nicolasgaldino/PokeDex#1]
CASO DE USO:
"Eu como um usuário realizei uma busca por nome 'pikachu' e fiquei satisfeito em vê-lo, mas gostaria de poder ver qual é o pokemon imediatamente anterior a ele na pokedex e o posterior"

BUG:
Após usar a busca por 'nome' do Pokémon, a aplicação retorna corretamente o bicho caso tenha escrito de maneira apropriada, porém ao tentar usar os botões 'anterior' e 'próximo' a aplicação quebra e disparar um comportamento não esperado.

INVESTIGAÇÃO e HIPÓTESES:
Aparentemente no o método "handleSubmit" em algum momento seta a variável "seachPokemon" como texto, quando os demais métodos esparam um número inteiro.

REGISTRO DO ERRO:
![opera_Dhk9q5tZO1](https://user-images.githubusercontent.com/2124022/180611090-a3afbabd-890b-490f-a0a7-1eac1c33bd06.gif)

LOG:
![opera_IuQQ2VPO2V](https://user-images.githubusercontent.com/2124022/180611113-bf7300e4-88ff-4b60-818b-4ba44d97136f.png)

**Comment by nicolasgaldino** [comment]
Ahh pode crer, valeu pelo alerta. 
A variável "searchPokemon" tá recebendo valores numéricos, não strings. Haha
Valeu pelo aviso, vou corrigir o quanto antes.

**Comment by nicolasgaldino** [comment]
@bakudas bug resolvido!
Obrigado pelo alerta. Vou trabalhar agora para melhorar o código e adicionar comentários.
