### ISSUE TITLE
Parabéns pelo projeto!

### ISSUE THREAD

**Issue by bakudas** [nicolasgaldino/PokeDex#2]
Meu caro, é muito gratificante ver os avanços nos seu estudos.

A execução do trabalho ficou bem interessante, percebi que escolheu um caminho mais enxuto e deu pra notar como utilizou a tarefa para aperfeiçoar os conceitos. Recomendo que tire um momento depois para dar uma revisada na lógica, refatorando e adicionando mais comentários ao longo da codificação (se pá escrevendo alguns testes unitários). Gostei muito do carinho que teve como a apresentação e implementação como um todo do projeto. Novamente, parabéns!

Forte abraço e bons estudos!
will

**Comment by nicolasgaldino** [comment]
Valeu Wil!
Vou melhorar bastante esse projeto. Estou pensando em criar card estilo aqueles dos anos 2000 quando vendiam nas bancas. Haha
